### ISSUE TITLE
This .ass file breaks it.

### ISSUE THREAD

**Issue by Calvin-Xu** [Calvin-Xu/mach3-cli#1]
I have no idea now...

Traceback (most recent call last):
  File "/usr/local/bin/mach3", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/mach3/cli.py", line 21, in main
    parse_result = recursive_index(dir_query)
  File "/usr/local/lib/python3.6/site-packages/mach3/subtitle_parse.py", line 39, in recursive_index
    all_dialogues.append(get_dialogues(file))
  File "/usr/local/lib/python3.6/site-packages/mach3/subtitle_parse.py", line 28, in get_dialogues
    doc = ass.parse(rawFile)
  File "/usr/local/lib/python3.6/site-packages/ass/document.py", line 290, in parse_file
    for i, line in enumerate(f):
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

[To Aru Kagaku no Railgun S[15].ass.zip](https://github.com/Calvin-Xu/mach3-cli/files/1822777/To.Aru.Kagaku.no.Railgun.S.15.ass.zip)

**Comment by Calvin-Xu** [comment]
Answer: the encoding of this file is UTF-16 LE. All the others are UTF-8...So solved.
